### ISSUE TITLE
Where to populate blank Environment field?

### ISSUE THREAD

**Issue by markhu** [QASymphony/jenkin-qtest-plugin#1]
Where does Environment data come from? When I try to type it into qTest, it errors out, and when I trie to type it into Jenkins, it does nothing. @qasdev 

qTest:

![image](https://cloud.githubusercontent.com/assets/239803/24271790/bd718990-0fd7-11e7-8be2-fd39421e6046.png)

Jenkins:

![image](https://cloud.githubusercontent.com/assets/239803/24271601/02720d68-0fd7-11e7-9e8e-7c0115903f7d.png)

**Comment by duongnapham** [comment]
Hi markhu,

Please help us submit your question to our ticket system, refer: https://support.qasymphony.com/hc/en-us/requests/new
We will provide you all the the detail explaination in our system.

Thanks,
Duong Pham

**Comment by markhu** [comment]
Filed: https://support.qasymphony.com/hc/en-us/requests/8908 and received a prompt response.
