### ISSUE TITLE
How to use this in a Jenkinsfile

### ISSUE THREAD

**Issue by qorrect** [QASymphony/jenkin-qtest-plugin#2]
Is there a way to use this from within a Jenkinsfile instead of GUI only ?  Thanks!

**Comment by gunivan** [comment]
Hi qorrect,

This is Trong from QASymphony and author of this plugin too,
Are you mean that Jenkins pipeline? We have a plan to support these plugin work with pipeline and would release in the next time, as of now it's not support to work with pipeline.

Best,
Trong.

**Comment by markhu** [comment]
This is important since Jenkins is encouraging all users to migrate to Jenkinsfile script since 2016.

**Comment by tamvanvo** [comment]
@markhu 
We have been supported Jenkins pipeline from version 1.3.0.
Thanks,
Tam
