### ISSUE TITLE
Support for concourse.ci ?

### ISSUE THREAD

**Issue by loafoe** [QASymphony/jenkin-qtest-plugin#5]
Hi,

Supporting Concourse would be great. Basic support could look something like:
- CLI tool which takes config from ENV
- Tool takes Junit XML reports as input
- Uploads to qTest Host

This would allow one to create a qtest resource which can be incorporated in a Concourse pipeline setup.

**Comment by duongnapham** [comment]
Hi loafoe,

Please help us submit your issue or any your request to our support system by using [this link](https://support.qasymphony.com/hc/en-us/requests/new#product_feature_suggestion) .

Thanks,

**Comment by loafoe** [comment]
@duongnapham  Done!
